### ISSUE TITLE
How to modify the function to calculate the AUROC

### ISSUE THREAD

**Issue by zzzyzh** [matejgrcic/Open-set-M2F#1]
Hi!
Thank you for your excellent work at first!
When I wish to apply this method directly to the cityscapes dataset, I get the following error:
`ValueError: multiclass format is not supported`
The shape of `mask_pred` is [100, 1024, 2048], and the shape of `mask_cls_` is [100, 20], what should I do?
Best regards.

**Comment by matejgrcic** [comment]
Hi,

AUROC requires binary ground truth. That is, a dataset with both inliers and outliers (e.g. fishyscapes, road anomaly, ...). Outliers should be assigned to class 1 and inliers to class 0. However, Cityscapes does not contain outlier pixels hence evaluating AUROC is not informative on that dataset. 

Hope this helps.

**Comment by zzzyzh** [comment]
Thanks a lot!
